; PlatformIO Project Configuration File
; https://docs.platformio.org/page/projectconf.html

[platformio]
core_dir = C:/pio/core
build_dir = C:/pio/build/hardware

[env:xiao_esp32c6]
platform = https://github.com/pioarduino/platform-espressif32/releases/download/stable/platform-espressif32.zip
board = seeed_xiao_esp32c6
framework = arduino
monitor_speed = 115200
upload_port = COM7
monitor_port = COM7
lib_deps =
    adafruit/Adafruit BusIO@^1.17.4
    ivanseidel/ArduinoThread@^2.1.1
